"""
inference.py — OpenEnv-compliant FastAPI server for Email Sorting Env.

Exposes every endpoint the OpenEnv validator checks:
  GET  /health        → {"status": "healthy"}
  GET  /metadata      → {"name": …, "description": …}
  GET  /schema        → {"action": …, "observation": …, "state": …}
  GET  /openapi.json  → (auto-generated by FastAPI)
  POST /reset         → ResetResponse  (observation, reward, done)
  POST /step          → StepResponse   (observation, reward, done)
  GET  /state         → current episode state
  POST /mcp           → minimal JSON-RPC 2.0 stub
"""

import os
import uvicorn
from fastapi import FastAPI, Body
from pydantic import BaseModel, Field
from typing import Any, Dict, List, Optional

from env import EmailSortingEnv
from models import Action, EmailLabel, Observation
from Agents import get_agent

# ── Config ─────────────────────────────────────────────────────────────────
AGENT_NAME = os.getenv("AGENT_NAME", "EnsembleAgent")
PORT = int(os.getenv("PORT", "7860"))

# ── App ────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Email Sorting OpenEnv",
    description="Email classification environment for the OpenEnv hackathon.",
    version="1.0.0",
)

# ── Shared state (single-episode, stateless across requests is fine) ──────
env: Optional[EmailSortingEnv] = None
agent = None
episode_rewards: List[float] = []
episode_step: int = 0
current_obs: Optional[Observation] = None
episode_done: bool = True


# ── Pydantic models for the OpenEnv contract ─────────────────────────────

class ResetRequest(BaseModel):
    seed: Optional[int] = None
    episode_id: Optional[str] = None
    difficulty: Optional[str] = None

class ObservationPayload(BaseModel):
    email_id: int = 0
    email_text: str = ""
    subject: Optional[str] = None
    sender: Optional[str] = None
    difficulty: Optional[str] = None
    step_number: int = 0
    total_steps: int = 0
    is_noisy: bool = False

class ResetResponse(BaseModel):
    observation: Dict[str, Any]
    reward: Optional[float] = None
    done: bool = False

class StepAction(BaseModel):
    label: str = "normal"
    confidence: Optional[float] = None

class StepRequest(BaseModel):
    action: Dict[str, Any]

class StepResponse(BaseModel):
    observation: Optional[Dict[str, Any]] = None
    reward: Optional[float] = None
    done: bool = False

class StateResponse(BaseModel):
    episode_id: Optional[str] = None
    step_count: int = 0
    done: bool = True
    rewards: List[float] = []


# ── Endpoints ─────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/metadata")
def metadata():
    return {
        "name": "email-sorting-env",
        "description": "Classify emails as spam, urgent, or normal. 40 realistic emails across easy/medium/hard difficulty.",
    }


@app.get("/schema")
def schema():
    return {
        "action": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "enum": ["spam", "urgent", "normal"],
                    "description": "Predicted email category",
                },
                "confidence": {
                    "type": "number",
                    "description": "Optional confidence score 0-1",
                },
            },
            "required": ["label"],
        },
        "observation": {
            "type": "object",
            "properties": {
                "email_id": {"type": "integer"},
                "email_text": {"type": "string"},
                "subject": {"type": "string"},
                "sender": {"type": "string"},
                "difficulty": {"type": "string"},
                "step_number": {"type": "integer"},
                "total_steps": {"type": "integer"},
                "is_noisy": {"type": "boolean"},
            },
        },
        "state": {
            "type": "object",
            "properties": {
                "episode_id": {"type": "string"},
                "step_count": {"type": "integer"},
                "done": {"type": "boolean"},
                "rewards": {"type": "array", "items": {"type": "number"}},
            },
        },
    }


@app.post("/reset", response_model=ResetResponse)
def reset(request: ResetRequest = Body(default_factory=ResetRequest)):
    global env, agent, episode_rewards, episode_step, current_obs, episode_done

    difficulty = request.difficulty
    env = EmailSortingEnv(difficulty=difficulty)
    agent = get_agent(AGENT_NAME)
    episode_rewards = []
    episode_step = 0
    episode_done = False

    obs = env.reset(difficulty=difficulty)
    current_obs = obs

    return ResetResponse(
        observation=obs.dict() if hasattr(obs, "dict") else obs.model_dump(),
        reward=None,
        done=False,
    )


@app.post("/step", response_model=StepResponse)
def step(request: StepRequest):
    global env, agent, episode_rewards, episode_step, current_obs, episode_done

    if env is None or episode_done:
        return StepResponse(observation=None, reward=0.0, done=True)

    action_data = request.action
    label_str = action_data.get("label", "normal")
    confidence = action_data.get("confidence", None)

    try:
        label = EmailLabel(label_str)
    except ValueError:
        label = EmailLabel.NORMAL

    action = Action(label=label, confidence=confidence)

    result = env.step(action)
    next_obs, reward, done, info = result

    episode_step += 1
    episode_rewards.append(reward.score if hasattr(reward, "score") else float(reward))
    episode_done = done

    if next_obs is not None:
        current_obs = next_obs
        obs_dict = next_obs.dict() if hasattr(next_obs, "dict") else next_obs.model_dump()
    else:
        obs_dict = None

    return StepResponse(
        observation=obs_dict,
        reward=reward.score if hasattr(reward, "score") else float(reward),
        done=done,
    )


@app.get("/state")
def get_state():
    return {
        "episode_id": None,
        "step_count": episode_step,
        "done": episode_done,
        "rewards": episode_rewards,
    }


@app.post("/mcp")
def mcp_handler(request: Dict[str, Any] = Body(...)):
    """Minimal JSON-RPC 2.0 stub for OpenEnv MCP validation."""
    method = request.get("method", "")
    request_id = request.get("id", 1)

    if method == "tools/list":
        return {
            "jsonrpc": "2.0",
            "id": request_id,
            "result": {
                "tools": [
                    {
                        "name": "reset",
                        "description": "Reset the email sorting environment",
                        "inputSchema": {"type": "object", "properties": {}},
                    },
                    {
                        "name": "step",
                        "description": "Submit an email classification action",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "label": {"type": "string", "enum": ["spam", "urgent", "normal"]},
                                "confidence": {"type": "number"},
                            },
                            "required": ["label"],
                        },
                    },
                ]
            },
        }

    return {
        "jsonrpc": "2.0",
        "id": request_id,
        "error": {
            "code": -32601,
            "message": f"Method not found: {method}",
        },
    }


# ── Main ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=PORT)
